{
  "datasource": {
    "type": "weikasoft-etpv3-datasource",
    "uid": "f9c8f6c0-34ba-4e22-9388-3bf129200933"
  },
  "gridPos": {
    "h": 22,
    "w": 6,
    "x": 18,
    "y": 0
  },
  "id": 5,
  "options": {
    "add100Percentage": true,
    "centerAlignContent": true,
    "overflow": "visible",
    "SVGBaseFix": true,
    "codeData": "{\n  \"text\": \"Random text\"\n}",
    "css": "* {\n  font-family: Open Sans;\n}\n\n.box {\n  font-size: 0.9vw;\n  border-radius: 10px;\n  padding: 5px 5px;\n  margin: 1% 1%;\n  width:40%;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  flex-direction: column;\n  /* background: linear-gradient(rgba(156, 154, 154, 1) 0%, rgba(235, 235, 235, 1) 64%, rgba(235, 235, 235, 1) 84%); */\n  border: 8px solid transparent;\n  /* color:black; */\n  /* filter: invert(100%); */\n  /* border-image: url(/public/img/metal-border.png) 30 stretch; */\n}\n\n.box-dark {\nbackground: rgb(31,31,31);\n\n/* background: linear-gradient(90deg, rgba(31,31,31,1) 3%, rgba(141,141,148,1) 27%, rgba(19,19,19,1) 100%); */\n}\n\n.box-container {\n  display: flex;\n  flex-direction: row;\n  flex-wrap: wrap;\n  text-align: center;\n}\n\n",
    "html": "<div class=\"box-container\" id=\"htmlgraphics-container\" >\n\n</div>\n",
    "renderOnMount": true,
    "onRender": "// Sets the value from the first series on every refresh\nconst htmlgraphicsContainer = htmlNode.getElementById('htmlgraphics-container');\nconst jhtmlgraphicsContainer = $(htmlgraphicsContainer);\njhtmlgraphicsContainer.empty();\nconst extraClass= theme.isDark ? \" box-dark\" : '';\n// const extraClass=  '';'\ndata.series[0].fields.forEach(f=>{\n    let v = f.values;\n    let display = f.display(v.get(v.length-1)); \n    jhtmlgraphicsContainer.append($(`<div class=\"box ${extraClass}\">${f.name} <br/>${display.text + (display.suffix || \"\")}</div>`))\n})\nconsole.log(theme)\n// htmlgraphicsContainer.style.color = theme.colors.text;\n",
    "dynamicData": false,
    "panelupdateOnMount": true,
    "onInit": "// // Sets the text from customProperties\n// const htmlgraphicsText = htmlNode.getElementById('htmlgraphics-text');\n\n// if (htmlgraphicsText) {\n//   htmlgraphicsText.textContent = customProperties.text;\n\n//   // Change the text color based on the theme\n//   if (theme.isDark) {\n//     htmlgraphicsText.style.color = 'green';\n//   } else {\n//     htmlgraphicsText.style.color = 'red';\n//   }\n// }\n"
  },
  "targets": [
    {
      "channels": [
        "DEPT",
        "LAGTIME",
        "LAGDEP",
        "DBTM",
        "BITRUN",
        "BPOS",
        "HKLD",
        "RPM",
        "WOB",
        "TORQUE_AVG",
        "SPP",
        "PCAS",
        "SPM1",
        "SPM2",
        "DC",
        "TFLO",
        "FLOWOUT",
        "MWIN",
        "MWOUT",
        "MTI",
        "MTOUT",
        "MCI",
        "MCO",
        "TANK1_VOL",
        "TANK2_VOL",
        "TANK3_VOL",
        "TANK4_VOL",
        "TANK5_VOL",
        "TANK6_VOL",
        "C1",
        "C2",
        "C3",
        "IC4",
        "NC4",
        "IC5",
        "NC5",
        "GAS_TOTAL",
        "CO2",
        "H2SLINE",
        "H2SPIT",
        "ECD_RT",
        "BITCOST",
        "SPM3",
        "TANK7_VOL",
        "TANK8_VOL",
        "TVD",
        "STAT",
        "GS_TSTK",
        "BITOFF",
        "KELLYIN",
        "HKS",
        "WOH_CALC",
        "FLOAT_WEIGHT",
        "ROP_INST",
        "ROP",
        "TD_TORQUE",
        "PUMPTOTAL",
        "STROKES1",
        "STROKES2",
        "STROKES3",
        "TOT_SPM",
        "VOP_INST",
        "VOP_MAVG",
        "FLOW",
        "TANK9_VOL",
        "TANK10_VOL",
        "PIT11",
        "PIT12",
        "TT1_VOL",
        "TVA",
        "PITT",
        "TVCA",
        "EC5",
        "IC6",
        "NC6",
        "H2",
        "H2SSHAKERS",
        "H2SCELLAR",
        "H2S5",
        "H2S6",
        "H2S7",
        "H2S8",
        "STRINGLEN",
        "CURPIPE",
        "BITNO",
        "BITSIZE",
        "BITTYPE",
        "BITIME",
        "BITDRILLTIME",
        "TOTALDAYS",
        "STANDSDONE",
        "STANDSTOGO",
        "TRIPOVERPULL",
        "SIGMA",
        "BDTV",
        "TORQUE_MAX",
        "GAINLOSS",
        "RIGTIME01",
        "BIT_REV",
        "GASA",
        "PV",
        "YP",
        "BITLOSS",
        "DSTRINGLOSS",
        "ANNLOSS",
        "SURFLOSS",
        "TT2_VOL",
        "LAGMWT",
        "LAGMTEMP",
        "MTOUT_LAGGED",
        "MCI_LAGGED",
        "SURF_RPM",
        "RPMMI",
        "FREE114",
        "ROP_MAVG",
        "FREE116",
        "FREE117",
        "FREE118",
        "FREE119",
        "FREE120"
      ],
      "datasource": {
        "type": "weikasoft-etpv3-datasource",
        "uid": "f9c8f6c0-34ba-4e22-9388-3bf129200933"
      },
      "etpResourceUri": "eml://witsml14/well(${well})/wellbore(${well})/log(LTD)",
      "mudLogUri": "",
      "refId": "A",
      "selectedChannels": [
        "DEPT",
        "DBTM",
        "LAGDEP",
        "LAGTIME",
        "HKLD",
        "WOB",
        "SPP",
        "TFLO",
        "TORQUE_AVG"
      ],
      "showFormationMarker": false,
      "streamMode": "LastValue"
    }
  ],
  "transparent": true,
  "type": "gapit-htmlgraphics-panel"
}